# Write your MySQL query statement below
SELECT D.NAME AS Department, E.NAME AS Employee, E.SALARY AS Salary
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPARTMENTID=D.ID AND
(E.DEPARTMENTID,E.SALARY) IN (
    SELECT DEPARTMENTID, MAX(SALARY) FROM EMPLOYEE
    GROUP BY DEPARTMENTID
);